### PR TITLE
Local authors posts link to local profiles.

### PR DESCRIPTION
**Pull request by JakeBrand**
No functionality to get remote profiles yet, so not implemented.

### CODE REVIEW

**Comment by JakeBrand** [comment]
Hold on a tick... Just one minute longer.

**Comment by zturchan** [comment]
Sorry, I was trying to check out your branch but ended up deleting it
because my local github didn't see it.  Carry on with your business,

Zak Turchansky

**Comment by JakeBrand** [comment]
Ok. Should be good to go now. I almost missed that last part.
You should be able to try it out and it should work. Should be good to merge.

**Comment by zturchan** [comment]
Yup it looks good, that's what i was gonna add XD.

Zak Turchansky

**Pull request merged**
