### PR TITLE
Api external test

### PR DESCRIPTION
**Pull request by varsis**
This contains an extensive test suite, it will not run on your machine unless you can run ./manage.py runserver

This tests our external api, using our server!

Running it:
nosetests tests

### CODE REVIEW

**Comment by grepme** [comment]
I added in Pillow so that Travis-CI runs your testsuite. Otherwise, this will occur:

ERRORS:
comments.Comment.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
    HINT: Get Pillow at https://pypi.python.org/pypi/Pillow or run command "pip install pillow".
posts.Post.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
    HINT: Get Pillow at https://pypi.python.org/pypi/Pillow or run command "pip install pillow".

**Comment by grepme** [comment]
Just going to wait on what Travis-CI says and then merge it manually...

**Comment by grepme** [comment]
I now changed the order of tests around and forgot the dummy data, so Django tests failed but your tests ran.

**Comment by varsis** [comment]
Awesome once this is done we can easily point out issues with a teams api too.

**Comment by grepme** [comment]
Wow, I'm smart. I missed manage.py.

**Comment by grepme** [comment]
Alright. Yours is running fine but @JakeBrand's tests still aren't. Still, worth a merge.

**Comment by varsis** [comment]
I was not expecting that to work on Travis ci

**Comment by grepme** [comment]
Well, it did :D. I'm fixing it up in another branch. Feel free to delete your own when ready.

**Pull request merged**
