### PR TITLE
Api foaf

### PR DESCRIPTION
**Pull request by varsis**
This isn't complete yet.

### CODE REVIEW

**Comment by JakeBrand** [comment]
Couple lingering print statements but it seems to be working just as well or better (with room to improve) as the master already is. I vote we merge it if only to have a more verbose All Posts page (and use the dummy.json fixture, because it includes Ashley's group which seems to be up at the moment).

**Comment by JakeBrand** [comment]
2 small bugs found:
1) Clicking "Add Friend" after following a link to local profile adds a blank-named friend to the Friends-search list.
2) Clicking the icon that looks like a picture beside a local friends name brings you to a 404 page (and the URL is projecthub.ca... not my localhost...)

**Comment by zturchan** [comment]
What's the status on this?

**Comment by varsis** [comment]
The one is because we have hard coded projecthub.ca the other one I’m looking into still.
Chris Pavlicek
http://www.varsisstudio.com

**Comment by zturchan** [comment]
Ok, cool.  Let me know Chris when you think this is in a good state and
ready to be merged and i'll record + test

Zak Turchansky

**Pull request merged**
